# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example Pipar Point'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/pipar-main.yml
    secrets: inherit
    with:
      board: '["pipar_point_left_3_0_0","pipar_point_right_3_0_0"]'
      custom_config: '["#define MIRYOKU_TIMELESS_HRM"]'
      alphas: '["colemakdh"]'
      clipboard: '["default"]'
      kconfig: '["CONFIG_ZMK_POINTING=y"]'
      # branches: '["petejohanson/zmk/core/move-to-zephyr-4-1"]'